name: Platform Tests & Build
on: [push]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        
    - name: Build binaries
      env:
        GOOS: linux
        GOARCH: amd64
      working-directory: .
      run: |
        md5sum -c rof/eqhost.txt
